### PR TITLE
PHP 8.0 support

### PR DESCRIPTION
**Pull request by dktapps**
The extent of my testing this is currently only just making sure all the tests pass when run in debug mode (--enable-debug).

There are 2 failing tests on my machine which I attribute to changes in OpenSSL (the tests are too brittle).

The third commit fixes a bug introduced by use with newer versions of OpenSSL (the algorithm name cases are now lowercased). I can separate this into another PR if desired.

### CODE REVIEW

**Comment by bukka** [comment]
Nice work! I did rebase and pushed the commits directly - somehow forgot that I don't have enabled squash and wanted to have commits separately. Anyway it's all there and you are still the author so should be all good :).

Thanks!

**Comment by bukka** [comment]
For the reference - the commits are following:
* https://github.com/bukka/php-crypto/commit/c3681e2e139c0c4c19af4ac4526c886dabd6f334
* https://github.com/bukka/php-crypto/commit/de57999e1e07e26e4cd2428c3e2cc9152c88a5c4
* https://github.com/bukka/php-crypto/commit/a821ab84ebea0b89b89571071aa340a137167807

**Comment by dktapps** [comment]
Awesome, thank you!

**Comment by dktapps** [comment]
@bukka btw, maybe good time for new tag / PECL release? current one is 4 years old 😄

**Comment by Jan-E** [comment]
> @bukka btw, maybe good time for new tag / PECL release? current one is 4 years old 😄

I ran into an error while compiling with PHP 5.6 (nts X64). I guess a new release sould drop PHP 5 support.

**Comment by dktapps** [comment]
I wasn't aware of the 5.6 build issue. I did have GitHub Actions test everything from 7.1 to 8.0 on Ubuntu, but I didn't test any earlier than 7.1 because getting older PHP versions to build on a recent OS is kinda pain in the ass. (Maybe dropping 7.0 is an option too? it's EOL anyway ...)

**Comment by Jan-E** [comment]
The errror:
```
crypto_cipher.obj : error LNK2019: unresolved external symbol PHPC_OBJ_FOR_PROP referenced in function php_crypto_cipher_set_algorithm_name
crypto_hash.obj : error LNK2001: unresolved external symbol PHPC_OBJ_FOR_PROP
```
PHP 7.1 & 7.2 are also EOL. I would not drop any PHP 7 version yet.

**Comment by dktapps** [comment]
@Jan-E you might have outdated `phpc` submodule. It was added here: https://github.com/bukka/phpc/commit/392752db2e6636748a8dd530ba0cd67c086e8a02

I updated the submodule pointer in this PR for the 8.0 build.

**Comment by Jan-E** [comment]
You were right. The submodule was not registerd and thus not updated.
```
rd phpc /s /q
git submodule init
git submodule update
```
Now it even compiles for PHP 5.3 (VC9, x86)

**Comment by bukka** [comment]
> @bukka btw, maybe good time for new tag / PECL release? current one is 4 years old

Yeah good idea :) Will try to find some time for that. Should probably fix those failing tests first though...

**Pull request closed without merging**
